/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const COGNITO_USER_POOL_ID = import.meta.env.VITE_APP_USER_POOL_ID;
const COGNITO_CLIENT_ID = import.meta.env.VITE_APP_USER_POOL_CLIENT_ID;
const REGION = import.meta.env.VITE_APP_REGION;

const awsmobile = {
	Auth: {
		region: import.meta.env.VITE_APP_REGION,
		userPoolId: import.meta.env.VITE_APP_USER_POOL_ID,
		userPoolWebClientId: import.meta.env.VITE_APP_USER_POOL_CLIENT_ID
	},
	API: {
		endpoints: [
			{
				name: 'PrismaApi',
				endpoint: import.meta.env.VITE_APP_API_URL,
				region: import.meta.env.VITE_APP_REGION
			}
		]
	}
};

export default awsmobile;
